Support waiting for containers to exit before continuing.
erikh/duct pull request #2
Opened 2021-01-19 03:54 UTC by shawnburke

Example scenario: some containers run DB init scripts, setup data, etc.

This adds a field which allows waiting for a container until it completes.

Manifest example:

* Container 1: Postgres
* Container 2 (WaitForExit), postgres init scripts, then exits
* Container 3: Service that uses (1)

```
c := New(Manifest{
		{
			Name:        "Exit",
			Command:     []string{"sleep", "1"},
			Image:       "debian:latest",
			WaitForExit: true,
		},
	}, WithNewNetwork("duct-test-network"))
```

If the process exits with a non-zero exit code, Duct will return a error.

2021-01-19 13:11 UTC, erikh commented
this one seems a bit more intricate; I'll go over it tomorrow. Ping me if you don't hear from me!

2021-01-20 02:38 UTC, erikh commented
let's resolve the conflicts before we move forward.

2021-01-20 20:45 UTC, shawnburke commented
OK merge completed.  I'm consuming this at work, so I realized that it also needs to dump the logs of containers that exit non-zero, so I added this as well, please take a look.

2021-01-21 00:24 UTC, erikh commented
Thanks! I'm working on a CI solution for this repository and it might be a day or so until I can get to this. We'll cut a release after this merge, so you don't need to use your fork after that.

2021-01-21 04:22 UTC, erikh requested changes
I did get a chance to look things over. Things look mostly good, thanks again for the contribution.

If you could rebase your changes against latest main, that might save me some merge trouble later.

2021-01-21 04:22 UTC, erikh commented on duct_test.go
> +			Command:     []string{"ls", "-123"},
let's make this:

```go
[]string{"sh", "-c", "exit 1"}
```

Depending on broken arguments to `ls` seems a bit brittle. Likewise, let's make the `sleep 1` do `exit 0` instead, it'll speed things up.

2021-01-21 11:39 UTC, erikh commented
hey -- carrying your patch to test the CI system. hope it's ok!

2021-01-21 11:56 UTC, erikh approved these changes
Thanks for the contribution!

2021-01-21 11:56 UTC, merged

2021-01-22 01:32 UTC, erikh commented
just pushed 0.3.0 as a result of your changes. thanks again!